### ISSUE TITLE
check compat with other floor mods

### ISSUE THREAD

**Issue by FluffierThanThou** [FluffierThanThou/StuffedFloors#24] opened 2020-04-26 21:05 UTC
Reported by: Thranos
Description:
Anyone know a way to make this and MoreFloors (1.1) a little more compatible? MoreFloors has some floor types this mod doesn't and vice versa, but running them both leads to a lot of duplicated floor types and some wonky behaviour.

**Comment by InsanityPrelude** [comment] 2020-09-14 20:24
Not a bug.  All player-buildable terrain types that aren't specifically bridges support Light, Medium, and Heavy structures.  If a floor type exists which can be placed on a terrain which a wall can't be placed on, and afterwards you can build a wall on that, then you've de-facto made a bridge.  (Or foundation, which is a different mod.)

Tellingly, this isn't a thing in the base game.  _All_ base game and royalty floor types require terrain that supports Heavy.  Because they all support anything that can be built on top of them and there's no mechanism for the game to remember "original-terrain-type" or something, if this was "fixed" then you could just build wood across terrain like soft sand and then build anything you wanted on it.  Added items which offer this functionality are beyond the scope of this mod.

**Comment by InsanityPrelude** [comment] 2020-09-14 20:26
The fix for this is six additional obsoletes for wooden floor types, basically.  If you want additional colors it's either Dubs Paint Shop or mods that add additional wood types in different colors for proper stuffing.

Reference PR #28

**Closed as completed** 2020-10-05 17:20 UTC
Labels: steam, unverified
